require('danemasen.opts')
require('danemasen.keymaps')
require('danemasen.autocmds')
require('danemasen.statusline')
require('danemasen.tabline')
require('danemasen.netrw')

require('danemasen.plugins.paq')
require('danemasen.plugins.treesitter')
require('danemasen.plugins.everforest')
require('danemasen.plugins.gitsigns')
require('danemasen.plugins.scrollbar')
require('danemasen.plugins.neogit')
require('danemasen.plugins.lualine')
require('danemasen.plugins.markit')
